export const xlsbookcolumns = [
  { key: "id", header: "Media Number" },
  { key: "createdAt", header: "Created At" },
  { key: "updatedAt", header: "Updated At" },
  { key: "rentalStatus", header: "Rental Status" },
  { key: "rentedDate", header: "Rented Date" },
  { key: "dueDate", header: "Due Date" },
  { key: "renewalCount", header: "Renewal Count" },
  { key: "title", header: "Title" },
  { key: "subtitle", header: "Subtitle" },
  { key: "author", header: "Author" },
  { key: "topics", header: "Topics" },
  { key: "imageLink", header: "Image Link" },
  { key: "isbn", header: "ISBN" },
  { key: "editionDescription", header: "Edition" },
  { key: "publisherLocation", header: "Publisher Location" },
  { key: "pages", header: "Pages" },
  { key: "summary", header: "Summary" },
  { key: "minPlayers", header: "Min Players" },
  { key: "publisherName", header: "Publisher" },
  { key: "otherPhysicalAttributes", header: "Attributes" },
  { key: "supplierComment", header: "Supplier Comment" },
  { key: "publisherDate", header: "Publication Date" },
  { key: "physicalSize", header: "Physical Size" },
  { key: "minAge", header: "Min Age" },
  { key: "maxAge", header: "Max Age" },
  { key: "additionalMaterial", header: "Additional Material" },
  { key: "price", header: "Price" },
  { key: "externalLinks", header: "Links" },
  { key: "userId", header: "Rented By" },
];

export const xlsusercolumns = [
  { key: "createdAt", header: "Created At" },
  { key: "updatedAt", header: "Updated At" },
  { key: "id", header: "ID" },
  { key: "lastName", header: "Last Name" },
  { key: "firstName", header: "First Name" },
  { key: "schoolGrade", header: "School Grade" },
  { key: "schoolTeacherName", header: "Teacher" },
  { key: "active", header: "Active" },
  { key: "eMail", header: "Email" },
];
